## Logistic Regression Implementation

In [1]:
from sklearn.datasets import load_iris

In [4]:
dataset = load_iris()

In [5]:
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [7]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
import pandas as pd
import numpy as np


In [13]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [14]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [16]:
df['target'] = dataset.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
df['target'].unique()

array([0, 1, 2])

In [20]:
# or df[df['target'] != 2]
df_copy = df[df['target'].isin([0,1])]

In [22]:
df_copy.target.unique()

array([0, 1])

In [50]:
# Independent features
X = df_copy.iloc[:, :-1]

# Dependentfeatures
y = df_copy.iloc[:, -1]

In [51]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state= 42)


In [54]:
X.shape, y.shape, X_train.shape, y_train.shape, X_test.shape, y_test.shape

((100, 4), (100,), (80, 4), (80,), (20, 4), (20,))

In [55]:
from sklearn.linear_model import LogisticRegression

In [56]:
classification = LogisticRegression(max_iter= 200)
classification

LogisticRegression(max_iter=200)

In [57]:
classification.fit(X_train, y_train)


LogisticRegression(max_iter=200)

In [58]:
y_pred = classification.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion metrix, Accuracy, Classification report



In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [60]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [61]:
print(accuracy_score(y_test, y_pred))

1.0


In [62]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross validation

In [63]:
## K-fold validation

from sklearn.model_selection import KFold

In [68]:
cv = KFold(n_splits = 5, shuffle = True)
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [69]:
from sklearn.model_selection import cross_val_score

In [71]:
cross_val_score(classification, X_train, y_train,
               scoring= 'accuracy',
               cv = cv)

# 5 different accuracies
# these are scores for all the cross validation experiments

array([1., 1., 1., 1., 1.])

In [72]:
scores = cross_val_score(classification, X_train, y_train,
               scoring= 'accuracy',
               cv = cv)

In [73]:
scores

array([1., 1., 1., 1., 1.])

In [74]:
np.mean(scores)

1.0

In [75]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [76]:
X

array([[ 2.56999479, -0.13019997,  3.16075093, ..., -1.93094078,
         3.26130366,  2.05692145],
       [ 0.34129317,  2.51321418, -0.80416572, ...,  6.24734437,
        -1.92769365,  2.9503149 ],
       [ 2.27539972,  3.36561455,  0.17164362, ...,  2.74693781,
         0.13492444,  2.00339547],
       ...,
       [ 0.5234359 ,  1.90466429,  0.93243365, ...,  1.53945231,
         1.90646166,  1.99458587],
       [ 1.33747921,  3.25859684,  0.78792366, ...,  5.18788314,
        -0.82071083,  3.51411431],
       [-0.98534299,  0.83919047,  2.5820803 , ...,  3.04705685,
         0.66885641,  3.32838496]])

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [80]:
complex_class_model=LogisticRegression(max_iter=200)

In [81]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [82]:
y_pred_complex=complex_class_model.predict(X_test)

In [83]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [85]:
## Cross Validatiuon
cv=KFold(n_splits=5)
cross_val_scores = cross_val_score(complex_class_model,X_train,y_train,cv=cv)
cross_val_scores

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [86]:
cross_val_scores.mean()

0.8099999999999999

In [88]:
cross_val_scores.min(), cross_val_scores.max()

(0.78125, 0.85625)

In [ ]:
# Go through the documentations, then only you will be able to learn